"""Compile one bundle into harness-native config (Claude Code + AGENTS.md).

Generated files carry a marker line so `agentic doctor` can detect hand-edits.
This is the 'Compile' step: author once, project into whatever harness you use.
"""
from __future__ import annotations

import json
import os

MARKER = "generated by agentic from .agentic/bundle.yaml — do not edit"

CAP_TO_TOOL = {
    "read": "Read",
    "edit": "Edit",
    "write": "Write",
    "bash": "Bash",
    "grep": "Grep",
    "glob": "Glob",
}


def _cli_wrapper_path() -> str:
    # <cli_root>/src/agentic/projector.py -> <cli_root>/agentic
    here = os.path.abspath(__file__)
    cli_root = os.path.dirname(os.path.dirname(os.path.dirname(here)))
    return os.path.join(cli_root, "agentic")


def _tools_for(role: dict) -> list[str]:
    return [CAP_TO_TOOL[c] for c in role.get("capabilities", []) if c in CAP_TO_TOOL]


def _agent_md(role: dict) -> str:
    tools = ", ".join(_tools_for(role))
    fm = [
        "---",
        f"name: {role['id']}",
        f"description: {role.get('role', role['id'])}",
    ]
    if tools:
        fm.append(f"tools: {tools}")
    fm.append("---")
    body = [f"<!-- {MARKER} -->", "", f"# {role['id']}", "", role.get("role", "")]
    if role.get("owns"):
        body += ["", "**Owns (exclusive):** " + ", ".join(role["owns"])]
    if role.get("pairs_with"):
        body += ["", "**Pairs with:** " + ", ".join(role["pairs_with"])]
    return "\n".join(fm) + "\n" + "\n".join(body) + "\n"


def _skill_md(phase: str, gate: dict | None) -> str:
    lines = [
        "---",
        f"name: {phase}",
        f"description: Lifecycle phase '{phase}' (projected from the bundle).",
        "---",
        f"<!-- {MARKER} -->",
        "",
        f"# Phase: {phase}",
        "",
        f"Run the `{phase}` phase of the lifecycle and emit its artifact.",
    ]
    if gate:
        lines += [
            "",
            f"**Gate after this phase:** `{gate['name']}` — requires: "
            + ", ".join(gate.get("requires", [])),
            "",
            "The orchestrator MUST NOT cross this gate until the required artifacts exist.",
        ]
    return "\n".join(lines) + "\n"


def _agents_md(data: dict) -> str:
    sdlc = data.get("sdlc", {})
    out = [f"<!-- {MARKER} -->", "", f"# {data.get('name')} — Agent Operating Model", ""]
    out += ["## Roles", ""]
    for r in sdlc.get("roles", []):
        owns = f" — owns `{', '.join(r['owns'])}`" if r.get("owns") else ""
        out.append(f"- **{r['id']}** ({', '.join(r.get('capabilities', []))}){owns}: {r.get('role','')}")
    lc = sdlc.get("lifecycle", {})
    out += ["", "## Lifecycle", "", "`" + " → ".join(lc.get("phases", [])) + "`", ""]
    gates = lc.get("gates", {})
    if gates:
        out += ["### Gates", ""]
        for gname, g in gates.items():
            out.append(f"- **{gname}** (after `{g.get('after')}`) requires: {', '.join(g.get('requires', []))}")
    sens = sdlc.get("sensitivity", {}).get("rules", [])
    if sens:
        out += ["", "## Sensitivity (Govern mode)", ""]
        for rule in sens:
            paths = ", ".join(rule.get("match", {}).get("paths", []))
            out.append(f"- `{paths}` → **{rule.get('level')}**: {', '.join(rule.get('require', []))}")
    out += ["", "_Changes to roles/lifecycle/gates are made in `.agentic/bundle.yaml`, then `agentic project`._"]
    return "\n".join(out) + "\n"


def _settings_json(root: str) -> str:
    wrapper = _cli_wrapper_path()
    cfg = {
        "hooks": {
            "PreToolUse": [
                {
                    "matcher": "Edit|Write|MultiEdit",
                    "hooks": [{"type": "command", "command": f"{wrapper} gate"}],
                }
            ]
        }
    }
    return json.dumps(cfg, indent=2) + "\n"


def _write(path: str, content: str, written: list):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    written.append(os.path.relpath(path, start=os.path.dirname(os.path.dirname(path))))


def project(root: str, data: dict) -> dict:
    """Generate harness config. Returns {'files': {relpath: content}} for reuse by doctor."""
    files: dict[str, str] = {}
    sdlc = data.get("sdlc", {})

    for r in sdlc.get("roles", []):
        files[os.path.join(".claude", "agents", r["id"] + ".md")] = _agent_md(r)

    lc = sdlc.get("lifecycle", {})
    gates = lc.get("gates", {})
    gate_by_phase = {g["after"]: {"name": n, **g} for n, g in gates.items() if g.get("after")}
    for phase in lc.get("phases", []):
        files[os.path.join(".claude", "skills", phase, "SKILL.md")] = _skill_md(
            phase, gate_by_phase.get(phase)
        )

    files[os.path.join(".claude", "settings.json")] = _settings_json(root)
    files["AGENTS.md"] = _agents_md(data)

    for rel, content in files.items():
        full = os.path.join(root, rel)
        os.makedirs(os.path.dirname(full), exist_ok=True)
        with open(full, "w") as f:
            f.write(content)
    return {"files": files}


def check_drift(root: str, data: dict) -> list[str]:
    """Return list of files that are missing or hand-edited vs a fresh projection."""
    expected = _regenerate(root, data)
    drift = []
    for rel, content in expected.items():
        full = os.path.join(root, rel)
        if not os.path.exists(full):
            drift.append(rel + " (missing)")
        elif open(full).read() != content:
            drift.append(rel + " (edited)")
    return drift


def _regenerate(root: str, data: dict) -> dict:
    files: dict[str, str] = {}
    sdlc = data.get("sdlc", {})
    for r in sdlc.get("roles", []):
        files[os.path.join(".claude", "agents", r["id"] + ".md")] = _agent_md(r)
    lc = sdlc.get("lifecycle", {})
    gates = lc.get("gates", {})
    gate_by_phase = {g["after"]: {"name": n, **g} for n, g in gates.items() if g.get("after")}
    for phase in lc.get("phases", []):
        files[os.path.join(".claude", "skills", phase, "SKILL.md")] = _skill_md(
            phase, gate_by_phase.get(phase)
        )
    files[os.path.join(".claude", "settings.json")] = _settings_json(root)
    files["AGENTS.md"] = _agents_md(data)
    return files
