"""Compile one bundle into harness-native config — the *Compile* step.

Author your fleet, lifecycle, and gates once in ``.agentic/bundle.yaml``; project
them into whatever harness you use. Every generated file carries a marker so
``agentic doctor`` can detect hand-edits, and a single :func:`render` function is
the source of truth for both writing and drift-checking (no duplicated logic).

Supported projection targets (declared in ``bundle.projections``):

- ``claude-code`` → ``.claude/agents/*.md`` + ``.claude/skills/*/SKILL.md`` + ``.claude/settings.json`` (hooks)
- ``cursor``      → ``.cursor/rules/*.mdc``
- ``agents-md``   → ``AGENTS.md`` (harness-neutral, human-readable)
"""
from __future__ import annotations

import json
import os

MARKER = "generated by agentic from .agentic/bundle.yaml — do not edit"

# capability (bundle) → Claude Code tool name
CAP_TO_TOOL = {
    "read": "Read",
    "edit": "Edit",
    "write": "Write",
    "bash": "Bash",
    "grep": "Grep",
    "glob": "Glob",
}


# ─────────────────────────────────────────────────────────── helpers
def _cli_wrapper_path() -> str:
    """Absolute path to the ``agentic`` launcher, for wiring hooks."""
    here = os.path.abspath(__file__)
    cli_root = os.path.dirname(os.path.dirname(os.path.dirname(here)))
    return os.path.join(cli_root, "agentic")


def _tools_for(role: dict) -> list[str]:
    return [CAP_TO_TOOL[c] for c in role.get("capabilities", []) if c in CAP_TO_TOOL]


def _gate_by_phase(lifecycle: dict) -> dict:
    gates = lifecycle.get("gates", {})
    return {g["after"]: {"name": n, **g} for n, g in gates.items() if g.get("after")}


# ─────────────────────────────────────────────────────── claude-code
def _claude_agent_md(role: dict) -> str:
    tools = ", ".join(_tools_for(role))
    lines = ["---", f"name: {role['id']}", f"description: {role.get('role', role['id'])}"]
    if tools:
        lines.append(f"tools: {tools}")
    lines += ["---", f"<!-- {MARKER} -->", "", f"# {role['id']}", "", role.get("role", "")]
    if role.get("owns"):
        lines += ["", "**Owns (exclusive):** " + ", ".join(role["owns"])]
    if role.get("pairs_with"):
        lines += ["", "**Pairs with:** " + ", ".join(role["pairs_with"])]
    return "\n".join(lines) + "\n"


def _claude_skill_md(phase: str, gate: dict | None) -> str:
    lines = [
        "---",
        f"name: {phase}",
        f"description: Lifecycle phase '{phase}' (projected from the bundle).",
        "---",
        f"<!-- {MARKER} -->",
        "",
        f"# Phase: {phase}",
        "",
        f"Run the `{phase}` phase of the lifecycle and emit its artifact.",
    ]
    if gate:
        lines += [
            "",
            f"**Gate after this phase:** `{gate['name']}` — requires: "
            + ", ".join(gate.get("requires", [])),
            "",
            "The orchestrator MUST NOT cross this gate until the required artifacts exist.",
        ]
    return "\n".join(lines) + "\n"


def _claude_settings_json() -> str:
    wrapper = _cli_wrapper_path()
    cfg = {
        "hooks": {
            "PreToolUse": [
                {
                    "matcher": "Edit|Write|MultiEdit",
                    "hooks": [{"type": "command", "command": f"{wrapper} gate"}],
                }
            ]
        }
    }
    return json.dumps(cfg, indent=2) + "\n"


# ──────────────────────────────────────────────────────────── cursor
def _cursor_rule_mdc(role: dict) -> str:
    """A Cursor rule (.mdc). Owned paths become globs so the rule auto-attaches;
    role with no owned paths applies always."""
    owns = role.get("owns", [])
    front = ["---", f"description: {role.get('role', role['id'])}"]
    if owns:
        front.append(f"globs: {', '.join(owns)}")
        front.append("alwaysApply: false")
    else:
        front.append("alwaysApply: true")
    front.append("---")
    body = [f"<!-- {MARKER} -->", "", f"# {role['id']}", "", role.get("role", "")]
    if owns:
        body += ["", "**Owns (exclusive):** " + ", ".join(owns)]
    if role.get("pairs_with"):
        body += ["", "**Pairs with:** " + ", ".join(role["pairs_with"])]
    return "\n".join(front) + "\n" + "\n".join(body) + "\n"


def _cursor_lifecycle_mdc(data: dict) -> str:
    sdlc = data.get("sdlc", {})
    lc = sdlc.get("lifecycle", {})
    lines = [
        "---",
        f"description: Lifecycle, gates, and sensitivity for {data.get('name')}",
        "alwaysApply: true",
        "---",
        f"<!-- {MARKER} -->",
        "",
        "# Lifecycle",
        "",
        "`" + " → ".join(lc.get("phases", [])) + "`",
    ]
    gates = lc.get("gates", {})
    if gates:
        lines += ["", "## Gates"]
        for gname, g in gates.items():
            lines.append(f"- **{gname}** (after `{g.get('after')}`) requires: {', '.join(g.get('requires', []))}")
    sens = sdlc.get("sensitivity", {}).get("rules", [])
    if sens:
        lines += ["", "## Sensitivity"]
        for rule in sens:
            paths = ", ".join(rule.get("match", {}).get("paths", []))
            lines.append(f"- `{paths}` → **{rule.get('level')}**: {', '.join(rule.get('require', []))}")
    return "\n".join(lines) + "\n"


# ─────────────────────────────────────────────────────────── agents.md
def _agents_md(data: dict) -> str:
    sdlc = data.get("sdlc", {})
    out = [f"<!-- {MARKER} -->", "", f"# {data.get('name')} — Agent Operating Model", "", "## Roles", ""]
    for r in sdlc.get("roles", []):
        owns = f" — owns `{', '.join(r['owns'])}`" if r.get("owns") else ""
        out.append(f"- **{r['id']}** ({', '.join(r.get('capabilities', []))}){owns}: {r.get('role','')}")
    lc = sdlc.get("lifecycle", {})
    out += ["", "## Lifecycle", "", "`" + " → ".join(lc.get("phases", [])) + "`", ""]
    gates = lc.get("gates", {})
    if gates:
        out += ["### Gates", ""]
        for gname, g in gates.items():
            out.append(f"- **{gname}** (after `{g.get('after')}`) requires: {', '.join(g.get('requires', []))}")
    sens = sdlc.get("sensitivity", {}).get("rules", [])
    if sens:
        out += ["", "## Sensitivity (Govern mode)", ""]
        for rule in sens:
            paths = ", ".join(rule.get("match", {}).get("paths", []))
            out.append(f"- `{paths}` → **{rule.get('level')}**: {', '.join(rule.get('require', []))}")
    out += ["", "_Edit `.agentic/bundle.yaml`, then run `agentic project` to regenerate._"]
    return "\n".join(out) + "\n"


# ──────────────────────────────────────────────────────── single source
def render(data: dict) -> dict[str, str]:
    """Return ``{relative_path: contents}`` for every file the bundle projects.

    This is the single source of truth used by both :func:`project` (write) and
    :func:`check_drift` (compare), so generated output can never diverge between
    the two paths.
    """
    files: dict[str, str] = {}
    sdlc = data.get("sdlc", {})
    roles = sdlc.get("roles", [])
    lifecycle = sdlc.get("lifecycle", {})
    targets = set(data.get("projections", ["claude-code", "agents-md"]))

    if "claude-code" in targets:
        for r in roles:
            files[os.path.join(".claude", "agents", f"{r['id']}.md")] = _claude_agent_md(r)
        gate_by_phase = _gate_by_phase(lifecycle)
        for phase in lifecycle.get("phases", []):
            files[os.path.join(".claude", "skills", phase, "SKILL.md")] = _claude_skill_md(
                phase, gate_by_phase.get(phase)
            )
        files[os.path.join(".claude", "settings.json")] = _claude_settings_json()

    if "cursor" in targets:
        for r in roles:
            files[os.path.join(".cursor", "rules", f"{r['id']}.mdc")] = _cursor_rule_mdc(r)
        files[os.path.join(".cursor", "rules", "lifecycle.mdc")] = _cursor_lifecycle_mdc(data)

    if "agents-md" in targets:
        files["AGENTS.md"] = _agents_md(data)

    return files


def project(root: str, data: dict) -> dict:
    """Render the bundle and write every file under ``root``."""
    files = render(data)
    for rel, content in files.items():
        full = os.path.join(root, rel)
        os.makedirs(os.path.dirname(full), exist_ok=True)
        with open(full, "w") as f:
            f.write(content)
    return {"files": files}


def check_drift(root: str, data: dict) -> list[str]:
    """Return files that are missing or hand-edited versus a fresh projection."""
    drift = []
    for rel, content in render(data).items():
        full = os.path.join(root, rel)
        if not os.path.exists(full):
            drift.append(f"{rel} (missing)")
        elif open(full).read() != content:
            drift.append(f"{rel} (edited)")
    return drift
